name: Harvester
version: 1.1.0
main: io.github.safyre.harvester.Harvester
api-version: 1.13
authors: [Safyre]
permissions:
  harvester.harvest:
    description: Allows you to harvest crops by right clicking them